Set JDK to newest version in Travis build
Due to the following compilation error in older JDKs:

    ┃  An exception has occurred in the compiler (1.8.0_151). Please file a bug against the Java compiler via the Java bug reporting page (http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com) for duplicates. Include your program and the following diagnostic in your report. Thank you.
    ┃  java.lang.NullPointerException
    ┃  	at com.sun.tools.javac.code.Types.removeWildcards(Types.java:601)
    ┃  	at com.sun.tools.javac.code.Types$DescriptorCache$FunctionDescriptor.getType(Types.java:362)
    ┃  	at com.sun.tools.javac.code.Types.findDescriptorType(Types.java:568)
    ┃  	at com.sun.tools.javac.code.Types.isFunctionalInterface(Types.java:585)
    ┃  	at com.sun.tools.javac.comp.DeferredAttr$CheckStuckPolicy.visitReference(DeferredAttr.java:1017)
    ┃  	at com.sun.tools.javac.comp.DeferredAttr$OverloadStuckPolicy.visitReference(DeferredAttr.java:1088)
    ┃  	at com.sun.tools.javac.tree.JCTree$JCMemberReference.accept(JCTree.java:1973)
    ┃  	at com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
    ┃  	at com.sun.tools.javac.comp.DeferredAttr$FilterScanner.scan(DeferredAttr.java:913)
    ┃  	at com.sun.tools.javac.comp.DeferredAttr$CheckStuckPolicy.<init>(DeferredAttr.java:980)
    ┃  	at com.sun.tools.javac.comp.DeferredAttr$OverloadStuckPolicy.<init>(DeferredAttr.java:1075)
    ┃  	at com.sun.tools.javac.comp.DeferredAttr$DeferredType.check(DeferredAttr.java:229)
    ┃  	at com.sun.tools.javac.comp.Resolve$MethodResultInfo.check(Resolve.java:1008)
    ┃  	at com.sun.tools.javac.comp.Resolve$4.checkArg(Resolve.java:835)
    ┃  	at com.sun.tools.javac.comp.Resolve$AbstractMethodCheck.argumentsAcceptable(Resolve.java:735)
    ┃  	at com.sun.tools.javac.comp.Resolve$4.argumentsAcceptable(Resolve.java:844)
    ┃  	at com.sun.tools.javac.comp.Resolve.rawInstantiate(Resolve.java:579)
    ┃  	at com.sun.tools.javac.comp.Resolve.selectBest(Resolve.java:1446)
    ┃  	at com.sun.tools.javac.comp.Resolve.findMethodInScope(Resolve.java:1633)
    ┃  	at com.sun.tools.javac.comp.Resolve.findMethod(Resolve.java:1704)
    ┃  	at com.sun.tools.javac.comp.Resolve.findMethod(Resolve.java:1677)
    ┃  	at com.sun.tools.javac.comp.Resolve.findFun(Resolve.java:1840)
    ┃  	at com.sun.tools.javac.comp.Resolve$8.doLookup(Resolve.java:2404)
    ┃  	at com.sun.tools.javac.comp.Resolve$BasicLookupHelper.lookup(Resolve.java:3097)
    ┃  	at com.sun.tools.javac.comp.Resolve.lookupMethod(Resolve.java:3348)
    ┃  	at com.sun.tools.javac.comp.Resolve.lookupMethod(Resolve.java:3333)
    ┃  	at com.sun.tools.javac.comp.Resolve.resolveMethod(Resolve.java:2400)
    ┃  	at com.sun.tools.javac.comp.Attr.visitIdent(Attr.java:3166)
    ┃  	at com.sun.tools.javac.tree.JCTree$JCIdent.accept(JCTree.java:2011)
    ┃  	at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:576)
    ┃  	at com.sun.tools.javac.comp.Attr.visitApply(Attr.java:1825)
    ┃  	at com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1465)
    ┃  	at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:576)
    ┃  	at com.sun.tools.javac.comp.Attr.visitReturn(Attr.java:1686)
    ┃  	at com.sun.tools.javac.tree.JCTree$JCReturn.accept(JCTree.java:1384)
    ┃  	at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:576)
    ┃  	at com.sun.tools.javac.comp.Attr.attribStat(Attr.java:645)
    ┃  	at com.sun.tools.javac.comp.Attr.attribStats(Attr.java:661)
    ┃  	at com.sun.tools.javac.comp.Attr.visitBlock(Attr.java:1124)
    ┃  	at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:909)
    ┃  	at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:576)
    ┃  	at com.sun.tools.javac.comp.Attr.attribStat(Attr.java:645)
    ┃  	at com.sun.tools.javac.comp.Attr.visitMethodDef(Attr.java:1013)
    ┃  	at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:778)
    ┃  	at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:576)
    ┃  	at com.sun.tools.javac.comp.Attr.attribStat(Attr.java:645)
    ┃  	at com.sun.tools.javac.comp.Attr.attribClassBody(Attr.java:4364)
    ┃  	at com.sun.tools.javac.comp.Attr.attribClass(Attr.java:4272)
    ┃  	at com.sun.tools.javac.comp.Attr.attribClass(Attr.java:4201)
    ┃  	at com.sun.tools.javac.comp.Attr.attrib(Attr.java:4176)
    ┃  	at com.sun.tools.javac.main.JavaCompiler.attribute(JavaCompiler.java:1248)
    ┃  	at com.sun.tools.javac.main.JavaCompiler.compile2(JavaCompiler.java:901)
    ┃  	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:860)
    ┃  	at com.sun.tools.javac.main.Main.compile(Main.java:523)
    ┃  	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
    ┃  	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
    ┃  	at org.codehaus.plexus.compiler.javac.JavaxToolsCompiler.compileInProcess(JavaxToolsCompiler.java:126)
    ┃  	at org.codehaus.plexus.compiler.javac.JavacCompiler.performCompile(JavacCompiler.java:174)
    ┃  	at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:1075)
    ┃  	at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:168)
    ┃  	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
    ┃  	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
    ┃  	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
    ┃  	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
    ┃  	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
    ┃  	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
    ┃  	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
    ┃  	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
    ┃  	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
    ┃  	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
    ┃  	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
    ┃  	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:955)
    ┃  	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:290)
    ┃  	at org.apache.maven.cli.MavenCli.main(MavenCli.java:194)
    ┃  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    ┃  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    ┃  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    ┃  	at java.lang.reflect.Method.invoke(Method.java:498)
    ┃  	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
    ┃  	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
    ┃  	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
    ┃  	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)